### PR TITLE
fix(client): Only create the funky object if message is not a string

### LINKED ISSUE #3296: Difficulty debugging errors, stack traces missing and/or poor formatting
### Expected behaviour

I'm hoping to see full stack traces, to aid in debugging.

### Actual behaviour

I see output like the following, which is making it difficult to debug:

<details>
<summary>output:</summary>

```
08 04 2019 20:37:40.725:INFO [karma]: Karma v2.0.5 server started at http://0.0.0.0:9876/
08 04 2019 20:37:40.728:INFO [launcher]: Launching browser CustomElectron with unlimited concurrency
08 04 2019 20:37:40.734:INFO [launcher]: Starting browser Electron
08 04 2019 20:37:41.312:INFO [Electron 2.0.18 (Node 8.9.3)]: Connected on socket UeP2147YwI328f5pAAAA with id 20256050
Electron 2.0.18 (Node 8.9.3) ERROR LOG: 'DEPRECATION:', 'Setting specFilter directly on Env is deprecated, please use the specFilter option in `configure`'
Electron 2.0.18 (Node 8.9.3) ERROR
  {
    "message": "Uncaught TypeError: Cannot read property 'default' of undefined\nat /Users/trusktr/src/trusktr+infamous/src/core/ImperativeBase.js:98:129\n\nundefined",
    "str": "Uncaught TypeError: Cannot read property 'default' of undefined\nat /Users/trusktr/src/trusktr+infamous/src/core/ImperativeBase.js:98:129\n\nundefined"
  }

Electron 2.0.18 (Node 8.9.3): Executed 0 of 0 ERROR (0.81 secs / 0 secs)
```

</details>

As you can see, the only hint is line `98`, which doesn't match the original source because that line seems to be relative to transpiled code. Plus, without the stack trace it is hard to imagine what is happening.

My karma config looks like the following:

<details>
<summary>karma.config.js:</summary>

```js

const CWD = process.cwd()
const glob = require('globby')
const fs = require('fs')
const mkdirp = require('mkdirp') // mkdir -p
const rmrf = require('rimraf') // rm -rf
const r = require('regexr').default

const testFiles = glob.sync([
    CWD+'/src/**/*.test.js',
    CWD+'/tests/**/*.js',
])

const config = fs.existsSync(CWD+'/builder.config.js') ? require(CWD+'/builder.config.js') : {}

rmrf.sync( CWD + '/.karma-test-build' )

testFiles.forEach(file => {
    const relativeFile = file.replace(CWD, '')
    const relativePath = dirname(relativeFile)

    mkdirp.sync( CWD + '/.karma-test-build' + relativePath )

    const nodeModulesToCompile = config.nodeModulesToCompile

    fs.writeFileSync( CWD + '/.karma-test-build' + relativeFile, `
        // NOTE, we don't use babel.config.js settings here, we can target a
        // more modern environment.
        require('@babel/register')({
            presets: [ ['@babel/preset-env', { targets: { node: 9 } }] ],
            plugins: [
                // We need to transpile the not-yet-official re-export syntax.
                '@babel/plugin-proposal-export-namespace-from',
                '@babel/plugin-proposal-export-default-from',
            ],
            sourceMap: 'inline',
            ${config.nodeModulesToCompile ? `
                ignore: [
                    // don't compile node_modules except for ones specified in the config
                    ${nodeModulesToCompile.map(moduleName => {
                        return r`/node_modules(?!\/${r.escape(moduleName)}\/)/`
                    })}
                ],
            ` : ''}
        })

        require( '${ file }' )
    ` )
})

const debugMode = false
// const debugMode = true

module.exports = function(config) {

    config.set({

        frameworks: ['jasmine', 'stacktrace'],
        reporters: ['spec'],
        port: 9876,  // karma web server port
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: false,
        singleRun: debugMode ? false : true,
        concurrency: Infinity,

        basePath: CWD,

        // Set up a "CustomElectron" launcher that extends karma-electron's
        // default "Electron" launcher, so that we can control options
        // (docs: // https://github.com/twolfson/karma-electron/tree/5.1.1#launcher-configuration)
        browsers: ['CustomElectron'],
        customLaunchers: {
            CustomElectron: {
                base: 'Electron',
                
                flags: debugMode ? [
                    // If in debug mode, this makes the electron window visible
                    // so that we can step through tests using devtools
                    '--show'
                    
                    // Alternatively to the --show option, we can use this
                    // option, then open chrome://inspect in Google Chrome and
                    // inspect from there.
                    // '--remote-debugging-port=9222',
                ] : [],
            }
        },
        
        files: [
            '.karma-test-build/**/*.js',
        ],
        preprocessors: {
            '.karma-test-build/**/*.js': ['electron'],
        },
        client: {
            // otherwise "require is not defined"
            useIframe: false,
            loadScriptsViaRequire: true,
        },

    })

}

function dirname(fullname) {
    if (typeof fullname !== 'string') throw new TypeError('expected a string')
    const parts = fullname.split('/')
    parts.pop()
    return parts.join('/')
}
```

</details>

Any ideas why the error output is so limited, or on how to make it show full stack traces? Maybe it isn't a karma problem, but a problem with a karma plugin? Thanks for any insight!

### Environment Details

- Karma version (output of `karma --version`): **2.0.5**
- Relevant part of your `karma.config.js` file: **see above**

### Steps to reproduce the behaviour

```sh
git clone https://github.com/trusktr/infamous.git
cd infamous
npm install
npm test
```

Note, `npm test` ultimately runs the script in `node_modules/builder-js-package/scripts/run-karma-tests.sh`:

<details>
<summary>run-karma-tests.sh:</summary>

```sh
xvfb-maybe \
	karma start ./node_modules/builder-js-package/config/karma.config.js
RESULT=$?

# remove the temporary folder
rm -rf ./.karma-test-build

exit $RESULT
```

</details>

So, another way in which you can run the tests directly is:

```sh
./node_modules/.bin/karma start ./node_modules/builder-js-package/config/karma.config.js
```

### PR DESCRIPTION
**Pull request by johnjbarton**
Fixes #3296

### CODE REVIEW

File: client/karma.js [hunk 1]
```diff
@@ -141,9 +141,11 @@ function Karma (socket, iframe, opener, navigator, location) {
       message += '\n\n' + error.stack
     }
 
-    // create an object with the string representation of the message to ensure all its content is properly
-    // transferred to the console log
-    message = {message: message, str: message.toString()}
+    if (typeof message !== 'string') {
```
Comment (kyliau) [inline client/karma.js]: the logic above this line assumes that `message` is a string, so perhaps it's better to do the following:

```
    var message = messageOrEvent
    if (typeof message === "string") {
        var location = getLocation(source, lineno, colno)
        if (location !== '') {
          message += '\nat ' + location
        }
        if (error) {
          message += '\n\n' + error.stack
        }
     }
     else {
      // create an object with the string representation of the message to ensure all its content is properly
      // transferred to the console log
      message = {message: message, str: message.toString()}
    }
```

Comment (johnjbarton) [reply client/karma.js]: Please take another look (the appveyor builds passed but failed to update github)
