### PR TITLE
fix(reporter): Fix #2930 causing error stack not to be parsed correctly

### LINKED ISSUE #2930: Karma 2 no longer correctly reports the original error stack when using source maps
### Expected behavior
When reporting an error and source maps are available the error stack should point to the original source line and column. The mocha-reporter shows this by using a format like in the following example:
_(webpack:///test/unittest/frontend/ods/convert--test.js:43:9 <- temp/karma_unittests/convert--test.js:712:10)_
```
at Context.<anonymous> (webpack:///test/unittest/frontend/ods/convert--test.js:43:9 <- temp/karma_unittests/convert--test.js:712:10)
```

### Actual behavior
Up to Karma 1.7 this worked as expected but starting with Karma 2.0 the [commit](https://github.com/karma-runner/karma/commit/34dc7d3) made a change in the definition of `URL_REGEXP` that causes the reporter to no longer recognize the lines in the error stack.
In the file `lib/reporter.js` when building `URL_REGEXP` the `urlRoot + '\\/?'` is now added before the `(base/|absolute)` and because `urlRoot` is always automatically post fixed with `/` the resulting regular expression now expects the url always to start with `/base` causing the matching to fail and to no longer correctly report the original file, line and column of the error stack.
```
at Context.<anonymous> (base/temp/karma_unittests/convert--test.js?6c85b6986d1a9cc153d2877ce8637a38a6b666ad:712:10)
```

### Environment Details

- Karma version (output of `karma --version`): 2.0.0
- Relevant part of your `karma.config.js` file
```
// Karma configuration

module.exports = function(config) {
  config.set({
    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

	// frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['mocha', 'chai'],

    // list of files / patterns to load in the browser
    files: [
      'dist/**/*.js'
    ],

    // list of files to exclude
    exclude: [
    ],

    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {
		'dist/**/*.js': ['sourcemap']
    },

    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['mocha'],

    // reporter options
    mochaReporter: {
      showDiff: true
  	},

    // web server port
    port: 9876,

    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_DEBUG,

    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: false,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'/*, 'Firefox', 'IE'*/],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: true,

    // Concurrency level
    // how many browser should be started simultaneous
    concurrency: 1,

	client: {
		// Capture all console output and pipe it to the terminal.
		captureConsole: true,
		mocha: {
			timeout: 60000
		}
	},

  });
}
```

### Steps to reproduce the behavior

1. Build a mocha unit test with a failing test and bundle it using webpack
2. Run the unit test using karma
3. Compare the results of the error stack between Karma 1.7 and 2.0

### PR DESCRIPTION
**Pull request by doberkofler**
Fixed a problem when config.urlRoot is set to '/' causing the error stack not to be parsed correctly and therefore source maps are not used.

### CODE REVIEW

**Comment by doberkofler** [comment]
@lusarz You have approved my changes, but there are a lot of unit tests failing in my push request and I guess i got it wrong. Did you already review the changes and problems?

**Comment by lusarz** [comment]
@doberkofler 
True, I shouldn't approve (although it doesn't matter because I'm not team member). I looked a little more closely to this issue, and I created minimal reproduction:
https://github.com/lusarz/karma-hello-world/tree/karma-sourcemap-issue-reproduction

Seems like this pull request solve problem, don't know why these unit tests fails - I'll try to figure it out.

**Comment by doberkofler** [comment]
@lusarz I noticed the failing unit tests but because most of them seem to be related to the the changes in 2.0, I did not feel as if I should just change them to “my” new behavior.
For me it was a simple regression, but I do not fully understand the background for the changes in 2.0.

File: lib/reporter.js [hunk 1]
```diff
@@ -9,7 +9,7 @@ var baseReporterDecoratorFactory = require('./reporters/base').decoratorFactory
 
 var createErrorFormatter = function (config, emitter, SourceMapConsumer) {
   var basePath = config.basePath
-  var urlRoot = config.urlRoot || ''
+  var urlRoot = config.urlRoot !== '/' ? config.urlRoot : ''
```
Comment (lusarz) [inline lib/reporter.js]: @doberkofler 
What about:

    var urlRoot = config.urlRoot === '/' ? '' : (config.urlRoot || '')

**Comment by doberkofler** [comment]
@lusarz Looks good to me. Just committed it to my fork to do some testing.

**Comment by lusarz** [comment]
@doberkofler 
I see on travis that unit tests are ok now. Travis throw one error:

    The command "if [ "$VALIDATE_COMMIT_MSG" == "true" ]; then ./scripts/validate-commit-msg.sh $TRAVIS_COMMIT; fi" failed and exited with 1 during .

Which seems to be related with format of commit message.

**Comment by doberkofler** [comment]
I have changed the commit message and the Travis build now passed.
The AppVeyor build still failed and I have no clue on what this is all about?

**Comment by lusarz** [comment]
@doberkofler 
Yeah, I noticed same issue on one of my pull request. It's not related with content of this pr (issue with `useragent` dependency). I was investigating a bit around it, and reported a few issues/points:
https://github.com/karma-runner/karma/pull/2913#issuecomment-364899798
https://github.com/3rd-Eden/useragent/issues/120

Seems that no authorized person has time to look at this :(

**Comment by lusarz** [comment]
Since [this pr](https://github.com/karma-runner/karma/pull/2937) is merged, appveyor build should works.

**Comment by doberkofler** [comment]
@dignifiedquire I've added a unit test

**Comment by dignifiedquire** [comment]
Thank you :octocat:

**Comment by lusarz** [comment]
@dignifiedquire Can I please for release into npm with this pull request?
