### PR TITLE
Fixed `EADDRINUSE` issue for tests running in parallel

### LINKED ISSUE #3065: Parallel run of tests gets error EADDRINUSE
### Expected behaviour

Parallel run will execute tests as expected

### Actual behaviour

Parallel run results in the following error
```
ERROR [karma]: { Error: listen EADDRINUSE 0.0.0.0:1111
    at Object._errnoException (util.js:1019:11)
    at _exceptionWithHostPort (util.js:1041:20)
    at Server.setupListenHandle [as _listen2] (net.js:1344:14)
    at listenInCluster (net.js:1385:12)
    at doListen (net.js:1494:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 1111 }
{ Error: Command failed: /node_modules/.bin/karma start /test/karma.conf.js

    at ChildProcess.exithandler (child_process.js:271:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:927:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

  killed: false,
  code: 1,
  signal: null,
  cmd: '/node_modules/.bin/karma start /test/karma.conf.js' }
```

### Environment Details

- Karma version (output of `karma --version`): 2.0.3+ (2.0.2 worked)
- Bluebird Queue 0.0.8 with `concurrency ` set as number > then 1

### Steps to reproduce the behaviour

1. Set tests to Bluebird queue
2. Run

(Running sequentially is fine.)

> I've found guy with very similar or the same problem - [Nx issue #606](https://github.com/nrwl/nx/issues/606)

### PR DESCRIPTION
**Pull request by sergei-startsev**
Fixed #3065 by passing `handle` that has already been bound to a port, see [server.listen](https://nodejs.org/api/net.html#net_server_listen_handle_backlog_callback).

### CODE REVIEW

File: lib/utils/net-utils.js [hunk 1]
```diff
@@ -4,29 +4,26 @@ const Promise = require('bluebird')
 const net = require('net')
 
 const NetUtils = {
-  isPortAvailable (port, listenAddress) {
-    return new Promise((resolve, reject) => {
-      const server = net.createServer()
+  getAvailablePort (port, listenAddress) {
+    function listen (port, listenAddress) {
```
Comment (lusarz) [inline lib/utils/net-utils.js]: Why we need to create listen function, and invoke it right after ? Can we return new Promise directly in `getAvailablePort` method ?

File: lib/server.js [hunk 2]
```diff
@@ -117,8 +117,11 @@ class Server extends KarmaEventEmitter {
       BundleUtils.bundleResourceIfNotExist('context/main.js', 'static/context.js')
     ])
       .then(() => NetUtils.getAvailablePort(config.port, config.listenAddress))
-      .then((port) => {
+      .then((bound) => {
```
Comment (lusarz) [inline lib/server.js]: Please consider using array decomposition: `then(([port, server]) => { ... } )`.

Comment (asapach) [reply lib/server.js]: I believe Node 4 doesn't support destructuring: https://node.green/#ES2015-syntax-destructuring--parameters

Comment (lusarz) [reply lib/server.js]: Ok, I see.

File: lib/utils/net-utils.js [hunk 3]
```diff
@@ -4,29 +4,26 @@ const Promise = require('bluebird')
 const net = require('net')
 
 const NetUtils = {
-  isPortAvailable (port, listenAddress) {
-    return new Promise((resolve, reject) => {
-      const server = net.createServer()
+  getAvailablePort (port, listenAddress) {
```
[the remark this answers is not in the document]
Comment (asapach) [reply lib/utils/net-utils.js]: *bind* is the correct verb - `findAndBindAvailablePort()`

File: lib/utils/net-utils.js [hunk 4]
```diff
@@ -4,29 +4,26 @@ const Promise = require('bluebird')
...
+            server.listen(++port, listenAddress)
+          } else {
+            reject(err)
+          }
+        })
 
-      server.listen(port, listenAddress, () => {
-        server.close(() => resolve(true))
+        server.listen(port, listenAddress, () => {
+          resolve([port, server])
```
Comment (asapach) [inline lib/utils/net-utils.js]: I believe you can get the port as `server.address().port`: https://nodejs.org/api/net.html#net_server_address
So maybe no need to pass it as a param.

File: lib/utils/net-utils.js [hunk 5]
```diff
@@ -4,29 +4,26 @@ const Promise = require('bluebird')
...
-        if (err.code === 'EADDRINUSE' || err.code === 'EACCES') {
-          resolve(false)
-        } else {
-          reject(err)
-        }
-      })
+        server.on('error', (err) => {
+          server.close()
+          if (err.code === 'EADDRINUSE' || err.code === 'EACCES') {
+            server.listen(++port, listenAddress)
```
Comment (asapach) [inline lib/utils/net-utils.js]: You're not passing the callback here - does the one below get invoked?

**Comment by sergei-startsev** [comment]
Folks, I've updated PR, could you take a look one more time?

File: lib/utils/net-utils.js [hunk 6]
```diff
@@ -4,29 +4,24 @@ const Promise = require('bluebird')
...
+      server
+        .on('error', (err) => {
+          server.close()
+          if (err.code === 'EADDRINUSE' || err.code === 'EACCES') {
+            server.listen(++port, listenAddress)
+          } else {
+            reject(err)
+          }
+        })
+        .on('listening', () => {
```
Comment (lusarz) [inline lib/utils/net-utils.js]: Really nice :+1:

File: lib/utils/net-utils.js (hunk 4 above)
Comment (lusarz) [reply lib/utils/net-utils.js]: @sergei-startsev What do you think about that ?

File: lib/utils/net-utils.js (hunk 6 above)
Comment (lusarz) [reply lib/utils/net-utils.js]: Just to be sure - did you tested if https://github.com/karma-runner/karma/issues/3011 don't occurs ?

Comment (sergei-startsev) [reply lib/utils/net-utils.js]: Since there's no clear repro steps, I've tried to test it on a project with thousands tests running in parallel - I haven't seen any issues.

File: lib/utils/net-utils.js [hunk 7]
```diff
@@ -4,29 +4,24 @@ const Promise = require('bluebird')
...
+          resolve(server)
```
Comment (sergei-startsev) [inline lib/utils/net-utils.js]: API has been changed a bit - now it returns only a bound server

File: test/unit/server.spec.js [hunk 8]
```diff
@@ -99,18 +106,27 @@ describe('server', () => {
       close: sinon.spy((callback) => callback && callback())
     }
 
-    sinon.stub(server._injector, 'get')
-      .withArgs('webServer').returns(mockWebServer)
-      .withArgs('socketServer').returns(mockSocketServer)
+    sinon
+      .stub(server._injector, 'get')
+      .withArgs('webServer')
+      .returns(mockWebServer)
```
Comment (asapach) [inline test/unit/server.spec.js]: minor: I would put `returns()` on the same line as the corresponding `withArgs()`

File: test/unit/server.spec.js [hunk 9]
```diff
@@ -99,18 +106,27 @@ describe('server', () => {
...
+      config = { port: 9876, listenAddress: '127.0.0.1' }
       sinon.spy(BundleUtils, 'bundleResourceIfNotExist')
-      sinon.stub(NetUtils, 'getAvailablePort').resolves(9876)
-      sinon.stub(server, 'get').withArgs('config').returns({ port: 9876, listenAddress: '127.0.0.1' })
+      sinon.stub(NetUtils, 'bindAvailablePort').resolves(mockBoundServer)
+      sinon.stub(mockBoundServer, 'address').returns({ port: 9877 })
+      sinon
+        .stub(server, 'get')
+        .withArgs('config')
+        .returns(config)
```
Comment (asapach) [inline test/unit/server.spec.js]: same here

**Comment by sergei-startsev** [comment]
Is there a chance to merge the PR?

**Comment by lusarz** [comment]
Yes, I approved it. You should be able to merge it yourself.

**Comment by sergei-startsev** [comment]
@lusarz I see `Only those with write access to this repository can merge pull requests.`

**Comment by lusarz** [comment]
@sergei-startsev Ok, I thought that it works in another way - merged :)

**Comment by sergei-startsev** [comment]
thanks!
