### PR TITLE
fix(client): avoid race between execute and clearContext

### LINKED ISSUE #3424: Race condition results in error "Some of your tests did a full page reload!"
### Expected behaviour

When running Karma with `singleRun = false` and `autoWatch = false` I would expect to be able to schedule a new run as soon as the 'old' run is completed.  

### Actual behaviour
A race condition in `clearContext` can report a false error in the new run.

### Environment Details

- Karma version (output of `karma --version`): `4.4.1`
- Relevant part of your `karma.config.js` file 

```js
{
  singleRun: false,
  autoWatch: false
}
```

### Steps to reproduce the behaviour

It is difficult to reproduce since it is a race condition. Essentially it can happen in this scenario:

```js
const karam = require('karma');
const server = new karma.Server({ singleRun: false, watch: false });
await server.start();
function runUntilError() {
  karma.runner.run({}, exitCode => {
    if(exitCode === 0) {
       runUntilError();
    } else {
       console.log('Aha! Run errored');
    }
  });
}
runUntilError()
```

### Triage

The problem is in the complete handler. Results are reported to the server _before_ the context is cleared:

https://github.com/karma-runner/karma/blob/6235e68bbf5a21b6723b652b3e9e09d627c2fad0/client/karma.js#L230-L242

The `clearContext` function sets the `reloadingContext` flag and navigates away.

https://github.com/karma-runner/karma/blob/6235e68bbf5a21b6723b652b3e9e09d627c2fad0/client/karma.js#L148-L152

Now, just before the browser navigates away, the `reloadingContext` is reset by the next execution:

https://github.com/karma-runner/karma/blob/6235e68bbf5a21b6723b652b3e9e09d627c2fad0/client/karma.js#L266

The concequence of this, is that the error is reported here:

https://github.com/karma-runner/karma/blob/6235e68bbf5a21b6723b652b3e9e09d627c2fad0/client/karma.js#L132

> Some of your tests did a full page reload!

However, I didn't reload any page.

### Workaround

If you set `client.clearContext` to false, the context will not be cleared and there is no risk of this race condition.

### PR DESCRIPTION
**Pull request by johnjbarton**
Add a delay in execute to ensure that reload events and clear context events are completed first.
Fixes #3424

### CODE REVIEW

**Comment by johnjbarton** [comment]
nicojs@ please review

File: client/karma.js [hunk 1]
```diff
@@ -234,11 +235,10 @@ function Karma (socket, iframe, opener, navigator, location, document) {
     }
 
     if (self.config.clearContext) {
-      // give the browser some time to breath, there could be a page reload, but because a bunch of
-      // tests could run in the same event loop, we wouldn't notice.
-      setTimeout(function () {
-        clearContext()
-      }, 0)
+      // A test could have incorrectly issued a navigate. To clear the context
+      // we will navigte the iframe. Delay ours to ensure the error from an
```
Comment (kyliau) [inline client/karma.js]: navigate (typo) to the iframe

File: client/karma.js [hunk 2]
```diff
@@ -259,24 +259,26 @@ function Karma (socket, iframe, opener, navigator, location, document) {
...
+    // Delay our navigation to the next event in case the clearContext has not completed.
+    setTimeout(function allowClearContextToComplete () {
+      // reset startEmitted and reload the iframe
+      startEmitted = false
+      self.config = cfg
+
+      navigateContextTo(constant.CONTEXT_URL)
+
+      if (self.config.clientDisplayNone) {
+        [].forEach.call(document.querySelectorAll('#banner, #browsers'), function (el) {
```
Comment (kyliau) [inline client/karma.js]: I think Array.from(document.querySelectorAll()).forEach(...) is more idiomatic, but I understand that this section is just change in indentation so I'll let you decide if we want to change this line in this PR

Comment (devoto13) [reply client/karma.js]: Or even `for (const el of document.querySelectorAll('#banner, #browsers')) { ... }`.

Comment (johnjbarton) [reply client/karma.js:271]: While I agree with these readability comments, I am reluctant to apply the change as this would break us on IE11
https://caniuse.com/#search=array.from
https://caniuse.com/#search=for...of
