### PR TITLE
fix(runner): Make exit code configurable when tests are failing

### LINKED ISSUE #1300: Configurable whether process should exit with non-zero exit code when tests failed?
We run tests on Jenkins using Karma and Grunt. Karma produces JUnit reports using the `karma-junit-reporter`, and we've configured Jenkins to set the build as unstable (yellow) if test failures are found in these report files.

The problem is that whenever a test fails, Karma (and Grunt) exits with a non-zero exit code and this makes the build failed (red).

I think the process still should fail in all those cases where the tests haven't been completely executed, for example when a browser has been disconnected.

Is there any way to configure this today? If not, I'll gladly provide a pull request.

### PR DESCRIPTION
**Pull request by andreaspsson**
Fixes #1300

### CODE REVIEW

File: lib/server.js [hunk 1]
```diff
@@ -133,6 +133,18 @@ class Server extends KarmaEventEmitter {
     return this._fileList ? this._fileList.refresh() : Promise.resolve()
   }
 
+  calculateExitCode (results, config) {
```
Comment (andreaspsson) [inline lib/server.js]: I implemented like this because I wanted to let `failOnEmptyTestSuite` work as it did before. But I think it is kind of strange that the `failOnEmptyTestSuite` flag overrides any error or disconnect and makes it always return success if it is false and there are no tests, an alternative implementation would be:

```javascript
if (!results.error && !results.disconnected) {
      if (results.success + results.failed === 0 && !config.failOnEmptyTestSuite) {
        this.log.warn('Test suite was empty.')
        return 0
      }
      if (!config.failOnFailingTestSuite) {
      return 0
    }
}
```

But that would slightly change the previous behaviour of `failOnEmptyTestSuite`.

File: lib/cli.js [hunk 2]
```diff
@@ -46,6 +46,13 @@ function processArgs (argv, options, fs, path) {
     options.failOnEmptyTestSuite = options.failOnEmptyTestSuite === 'true'
   }
 
+  if (helper.isString(options.failOnFailingTestSuite)) {
+    options.failOnFailingTestSuite = options.failOnFailingTestSuite === 'true'
+  } else if (typeof options.failOnFailingTestSuite === 'undefined') {
+    // Default value to true, to avoid chanching application default behaviour
```
Comment (johnjbarton) [inline lib/cli.js]: what is chanching?

File: lib/server.js (hunk 1 above)
Comment (johnjbarton) [reply lib/server.js]: It's hard to figure out all of the cases here, because the exitcode computation is shared between lib/server and lib/browser_collection. I would rather we do it in one place.

Doing the calculation here means we end up passing a different value of results.exitCode to reporters (via run_complete event).  So computing in browser_collection would be better.

Part of the calculation depends on `config`, not currently available in browser_collection.

How about doing all of the work in browser_collection with getResult(config, singleRunBrowserNotCaptured) or even getResult(failOnEmptyTestSuite, failOnFailingTestSuite, singleRunBrowserNotCaptured) ? 

That is, your calculateExitCode moves to that file and here we do the same thing as executor,
call getResults() and emit run_complete.

And I agree that `failOnEmptyTestSuite` should have only one effect: a test that would otherwise exit 0 should exit 1 if it ran no tests.

I hope this is clear.

File: lib/cli.js (hunk 2 above)
Comment (andreaspsson) [reply lib/cli.js]: I want to keep karma exit with failure unless the new argument is set, as it did before. In new version of the patch I updated the logic using the flag instead, so no default value is needed in `cli.js` to achieve this

**Comment by andreaspsson** [comment]
@johnjbarton Updated patch after you comments

File: lib/server.js (hunk 1 above)
Comment (andreaspsson) [reply lib/server.js]: I saw now that my reasoning about `failOnEmptyTestSuite` was not 100% correct. If no tests are executed `results.error` is true when the code reaches this point, so it suppresses errors, but it would also have suppressed exit codes generated by `results.disconnected` being true in the case of no tests was executed

File: lib/browser_collection.js [hunk 3]
```diff
@@ -46,7 +46,24 @@ class BrowserCollection {
...
+      return 1
+    }
+    if (results.success + results.failed === 0 && !failOnEmptyTestSuite) {
+      return 0
+    }
+    if (results.error) {
+      return 1
+    }
+    if (failOnFailingTestSuite === false) {
+      // No errors found, always return success
```
Comment (johnjbarton) [inline lib/browser_collection.js]: I think the comment would be clearer something like:
```
// Tests executed without infrastructure error, exit with 0 independent of test status.
```
Otherwise we are all tangled up in which fail and which error.

File: lib/browser_collection.js [hunk 4]
```diff
@@ -46,7 +46,24 @@ class BrowserCollection {
...
 
-  getResults () {
+  calculateExitCode (results, singleRunBrowserNotCaptured, failOnEmptyTestSuite, failOnFailingTestSuite) {
+    if (results.disconnected || singleRunBrowserNotCaptured) {
+      return 1
+    }
+    if (results.success + results.failed === 0 && !failOnEmptyTestSuite) {
+      return 0
+    }
+    if (results.error) {
```
Comment (johnjbarton) [inline lib/browser_collection.js]: I believe that at least some user errors (syntax?) come out as results.errors rather than result.failed.  But it's your feature to decide, or maybe try it and see.

Comment (andreaspsson) [reply lib/browser_collection.js]: Yes, syntax errors will set `results.error` to true. But from my point of view that is an other thing than a failure and shall not lead to a successful exit code
The syntax error will not generate a test failure in the generated test report, and may then be missed if hidden by the `failOnEmptyTestSuite` flag

File: lib/browser_collection.js (hunk 3 above)
Comment (andreaspsson) [reply lib/browser_collection.js]: Updated comment

**Comment by sambernet** [comment]
@johnjbarton and @andreaspsson:

After struggling with the problems caused by #1300 I was very pleased to see this has actually been resolved 🍾 🎆 

Sending lots of good _karma_ to you guys 😁 

Anyway it took me more research to arrive here than necessary, because the new flag does not seem to be documented (yet) [in the 3.0 docs](http://karma-runner.github.io/3.0/config/configuration-file.html).

Is there a good reason for that or is it just missing? I'm aware of the `3.0` in the path and the fact that the new flag was released in `3.1`, but I didn't find any newer docs either...

**Comment by johnjbarton** [comment]
A PR for docs always welcome.
