### PR TITLE
Better string representation of errors

### LINKED ISSUE #2711: Improve Error Message Handling
### Expected behaviour
When the execution of some test fails, the error message should be fully transferred to the console log for debugging purposes.

### Actual behaviour
Currently, when an error occurs e.g. inside a promise inside a zone.js, the error message is only partially transferred to the console. This is due to the JSON.stringify() representation of the message not containing all parts of the error message.

E.g. the console log might only show
```
{
    "originalErr": {},
    "__zone_symbol__currentTask": {
      "type": "microTask",
      "state": "notScheduled",
      "source": "Promise.then",
      "zone": "<root>",
      "cancelFn": null,
      "runCount": 0
    }
  }

Executed 0 of 0 ERROR 
```
which tells you nothing about the actual problem, which can be found with message.toString() in the `this.error()` method in https://github.com/karma-runner/karma/blob/master/client/karma.js#L116
In our case this resulted in
```
Error: (SystemJS) Object prototype may only be an Object or null: undefined
TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf 
```

### Environment Details

- Karma version 1.6.0

### PR DESCRIPTION
**Pull request by macjohnny**
Resolves #2711

Before:
```
Chrome 59.0.3071 (Mac OS X 10.12.3) ERROR
 {
      "originalErr": {},
      "__zone_symbol__currentTask": {
        "type": "microTask",
        "state": "notScheduled",
        "source": "Promise.then",
        "zone": "<root>",
        "cancelFn": null,
        "runCount": 0
      }
  }
Chrome 59.0.3071 (Mac OS X 10.12.3): Executed 0 of 0 ERROR (1.348 secs / 0 secs)
```

After:
```
Chrome 59.0.3071 (Mac OS X 10.12.3) ERROR
 {
    "message": {
      "originalErr": {},
      "__zone_symbol__currentTask": {
        "type": "microTask",
        "state": "notScheduled",
        "source": "Promise.then",
        "zone": "<root>",
        "cancelFn": null,
        "runCount": 0
      }
    },
    "str": [
      "Error: (SystemJS) Object prototype may only be an Object or null: undefined",
      "    TypeError: Object prototype may only be an Object or null: undefined",
      "        at setPrototypeOf (<anonymous>)",
      "        at __extends$1 (dist/bundles/my-bundle.umd.js:2258:9)",
    ]
  }
Chrome 59.0.3071 (Mac OS X 10.12.3): Executed 0 of 0 ERROR (1.348 secs / 0 secs)
```

### CODE REVIEW

**Comment by macjohnny** [comment]
I signed it!

File: client/karma.js [hunk 1]
```diff
@@ -112,7 +112,12 @@ var Karma = function (socket, iframe, opener, navigator, location) {
     if (url) {
       message = msg + '\nat ' + url + (line ? ':' + line : '')
     }
-
+    
+    // create an object with the string representation of the message to ensure all its content is properly 
+    // transferred to the console log
+    message = {message: message, str: message.toString().replace(/\t/g, "    ").split("\n")}
```
Comment (wesleycho) [inline client/karma.js]: The `replace` and `split` parts should probably be removed.

Also, this line changes the message variable's type from string to an object - this probably means that tests have to be updated.

Comment (macjohnny) [inline client/karma.js]: the replace and split parts are for nicer output display in the console, since the object is converted to json. 
With the split and replace, you get 
```
"str": [
      "Error: (SystemJS) Object prototype may only be an Object or null: undefined",
      "    TypeError: Object prototype may only be an Object or null: undefined",
      "        at setPrototypeOf (<anonymous>)",
      "        at __extends$1 (dist/bundles/my-bundle.umd.js:2258:9)",
    ]
```
instead of 

```
"str": "Error: (SystemJS) Object prototype may only be an Object or null: undefined\n\tTypeError: Object prototype may only be an Object or null: undefined\n\tat setPrototypeOf (<anonymous>)\n\tat __extends$1 (dist/bundles/my-bundle.umd.js:2258:9)",
```

Comment (macjohnny) [inline client/karma.js]: the variable type is not changed, the message already is an object that will later on be converted to a string with JSON.stringify()

Comment (macjohnny) [inline client/karma.js]: the message might be a string or an object

**Comment by macjohnny** [comment]
@wesleycho could you have a look at this again? this patch really helped me a lot when investigating preliminary import / systemjs issues that prevented the tests from being run and log a useful message.

**Comment by macjohnny** [comment]
@wesleycho could you please have a look at this again?

**Comment by larsduelfer** [comment]
I would also highly appreciate if this change is going to be integrated.

**Comment by macjohnny** [comment]
@EzraBrooks I can understand the formatting should not be done here. but since the message *can* be an object (which is the reason for this PR), it should be ok to transform it to a different object as I suggest in this PR.  would you accept this PR if I removed the `.replace(/\t/g, "    ").split("\n")` part?

**Comment by EzraBrooks** [comment]
Thanks, I’ll approve it once the CI checks complete.

**Comment by macjohnny** [comment]
@EzraBrooks it seems there is a problem with the travis ci build retrieving some commit message. however, all other tests pass. could you please have a look at it?

**Comment by EzraBrooks** [comment]
Please squash your commits into one that follows Karma’s naming conventions - Travis is failing on commit message validation.

**Comment by EzraBrooks** [comment]
Sorry, to clarify.. the commit messages all have a leading type on them. In this case, I would recommend `feat: better string representation of errors`.

**Comment by macjohnny** [comment]
@EzraBrooks done, waiting for the CI to complete

**Comment by EzraBrooks** [comment]
Looks like ESLint has a few style complaints.

**Comment by macjohnny** [comment]
@EzraBrooks I updated the PR, hope it is fine now
