### PR TITLE
fix(file-list): refresh resolves before 'file_list_modified' event

### LINKED ISSUE #1550: Runner race condition of stale files on subsequent runs
Noticed behavior:
using karma start and karma run, multiple executions of karma run results in seeing stale files / results.

This is because the web-server gets the file-list from the last file_list_modified event.  Runner test execution is scheduled after file-list refresh resolves.  This results in a race condition because the event is now emitted late because of a newly introduced trailing throttle.

### PR DESCRIPTION
**Pull request by thetrevdev**
file-list - file_list_modified should be emitted before refresh promise resolves

Runner test execution is scheduled after file-list refresh resolves.  The web-server gets the file-list from the last file_list_modified event. This was resulting in a race condition where the web server would grab a stale file list.

Closes #1550

### CODE REVIEW

File: lib/file-list.js [hunk 1]
```diff
@@ -70,20 +70,20 @@ var List = function (patterns, excludes, emitter, preprocess, batchInterval) {
...
-      leading: false
-    })
-  }
-}
+    }
+    var throttledEmit = _.throttle(emit, self._batchInterval, {leading: false})
+    self._emitModified = function (immediate) {
+      immediate ? emit() : throttledEmit()
+    }
+  }())
```
Comment (Dignifiedquire) [inline lib/file-list.js]: No need to hide these so much, you can just put the outside the constructor like this

```js
function emit (self) {...}
function throttledEmit(self) {...}

...

self._emitModified = function (immediate) {
  immediate ? emit(self) : throttledEmit(self)
}
```

**Comment by Dignifiedquire** [comment]
Thanks I left some inline comments

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 86ab6e425fcd26b1fc245238deeaad35ba3374ce
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at http://karma-runner.github.io/0.13/dev/git-commit-msg.html

---
This message was auto-generated by https://gitcop.com

**Comment by thetrevdev** [comment]
Updated.  Not sure why my build is failing on travis eslint for a file i didn't change.

**Comment by Dignifiedquire** [comment]
Thanks could you rebase onto the latest master please?

**Comment by thetrevdev** [comment]
done

**Comment by Dignifiedquire** [comment]
Thanks

**Comment by Dignifiedquire** [comment]
Damn can't merge anymore cause I merged the other one first.

**Comment by thetrevdev** [comment]
Rebased

**Comment by Dignifiedquire** [comment]
Thanks :octocat:
