### PR TITLE
fix(file-list): ensure patterns are comparable

### LINKED ISSUE #2194: karma v1.0.0: You need to include some adapter that implements __karma__.start method!
After upgrading our project from karma v0.13.22 to v.1.0.0 we get following error: 
`You need to include some adapter that implements __karma__.start method!` 

Here is a the repo: https://github.com/SerkanSipahi/app-decorators

##### Reproducing error:
```
git clone https://github.com/SerkanSipahi/app-decorators.git
cd app-decorators
// change in package.json karma to 1.0.0
make install
make compile
make test
```

Anyone have an idea What causes this error ?

### PR DESCRIPTION
**Pull request by dignifiedquire**
Thanks to @m-a-r-c-e-l-i-n-o for pointing me in the right direction
Fixes #2194

This supersedes #2255 

Also fixes 
- https://github.com/karma-runner/karma-jasmine/issues/127
- https://github.com/karma-runner/karma-mocha/issues/102
- https://github.com/karma-runner/karma/issues/2237

### CODE REVIEW

File: lib/file-list.js [hunk 1]
```diff
@@ -230,6 +231,13 @@ Object.defineProperty(List.prototype, 'files', {
     var lookup = {}
     var included = {}
     this._patterns.forEach(function (p) {
+      // This needs to be here sadly, as plugins are modifiying
+      // the _patterns directly resulting in elements not being
```
Comment (tamird) [inline lib/file-list.js]: @dignifiedquire for my own edification, can you give an example of a plugin doing this? Specifically, is [karm-jspm](https://github.com/Workiva/karma-jspm) doing this?

**Comment by dignifiedquire** [comment]
yes this is one place https://github.com/Workiva/karma-jspm/blob/master/src/init.js#L106

**Comment by tamird** [comment]
Ah, understood. LGTM.
