### PR TITLE
fix(server): Report original error message

### LINKED ISSUE #3414: Original error message is ignored by server
Errors of plugins like:
* [karma-browserstack-launcher](https://github.com/karma-runner/karma-browserstack-launcher)
* [karma-cbt-launcher](https://github.com/karma-runner/karma-cbt-launcher)
are not displayed in:

https://github.com/karma-runner/karma/blob/1fc51b01ec9ce0aa402ac68beb66780cb10cd96b/lib/server.js#L397-L398

&

https://github.com/karma-runner/karma/blob/1fc51b01ec9ce0aa402ac68beb66780cb10cd96b/lib/server.js#L402-L403

I run three grab a debugger several times to understand what went wrong. I think this can be improved.

Related: #3342

### PR DESCRIPTION
**Pull request by Borewit**
Display original error message of plugins like: 
* [karma-browserstack-launcher](https://github.com/karma-runner/karma-browserstack-launcher)
* [karma-cbt-launcher](https://github.com/karma-runner/karma-cbt-launcher)

Fixes #3414

### CODE REVIEW

**Comment by Borewit** [comment]
@googlebot I signed it!

File: lib/server.js [hunk 1]
```diff
@@ -395,12 +395,12 @@ class Server extends KarmaEventEmitter {
     }
 
     processWrapper.on('unhandledRejection', (error) => {
-      this.log.error('UnhandledRejection')
+      this.log.error(`UnhandledRejection: ${error.message}`)
```
Comment (johnjbarton) [inline lib/server.js]: JS can throw any type, `Error` or not.  So I think these need to be eg `${error.message || String(error)}`

Comment (trusktr) [reply lib/server.js]: If `error` is `undefined` or `null` for whatever reason, that line will have a new error trying to access `.message`. Hopefully that doesn't happen, but maybe it should be `(error && error.message) || String(error)`?

**Comment by trusktr** [comment]
@johnjbarton @Borewit Are these changes by chanced related to https://github.com/karma-runner/karma/issues/543 and https://github.com/karma-runner/karma/issues/1268 in any way?

**Comment by trusktr** [comment]
In particular, regarding those two issues, see my comment at the bottom: https://github.com/karma-runner/karma/issues/543#issuecomment-594069926

**Comment by Borewit** [comment]
> Are these changes by chanced related to #543 and #1268 in any way?

I don't think it is the exact same issue. 

In this case a message `UnhandledRejection` was printed to the console, without providing (printing) any further detail.
