### PR TITLE
fix: check for available port before start server (fix #1476, fix #3011)

### LINKED ISSUE #1476: proxy doesn't know if karma webserver runs on different port than originally configured
I'm using karma to test a project loaded by systemjs. For lack of a better way, my karma config depends heavily on use of proxies to rewrite paths (but I'm proxying back to karma's internal webserver, not a different webserver).

I'm also running these tests via a parallel test runner that runs several copies of karma. The first karma starts up on the port configured in karma.conf.js (9050 for me). The second one gets EADDRINUSE, logs "port 9050 in use", and happily rolls onto port 9051.

The problem is that karma configures the proxy with the port specified via config (thanks to https://github.com/karma-runner/karma/pull/1007) falling back to default 443/80 if the config doesn't specify. And karma configures the proxy library before it calls listen on its internal webserver, that is, before it discovers the port conflict and starts the webserver on a different port. And when it does discover the port conflict, it never tells the proxy library.

The result in my parallel test runner scenario is this: I start N copies of karma, they start their internal webservers on N different ports starting at 9050, but they've all configured their proxy to proxy to 9050. So all the proxied requests go to the webserver for the first karma instance to start. This actually works out better than you might expect, since they're all serving the same code... until the first karma test passes and exits (the batch tests run in single-run mode), and the rest of the tests keep trying to talk to the webserver that just exited.

This is easy to repro without the parallel scenario; any port conflict will do:
- take any karma test that has a config which proxies requests back to the internal webserver
- `netcat -lp [the port the karma config uses]`
- run the karma test

You'll see karma itself log "port in use" and increment until it finds an open port, but continue throwing proxied requests at the originally configured port.

A brute force fix for this is to defer evaluation of the proxyConfig port until it's actually needed, by which time karma's listening on the right port. A cleaner fix that doesn't rely on getters would probably have the outer glue code that starts everything wait till the internal webserver owns a port and then tell the proxy code explicitly to use that port. The initialization order and data flow is not very explicit thanks to DI so it's not immediately obvious to me how to accomplish that.

```
diff --git a/node_modules/karma/lib/middleware/proxy.js b/node_modules/karma/lib/middleware/proxy.js
index e439c52..9485965 100644
--- a/node_modules/karma/lib/middleware/proxy.js
+++ b/node_modules/karma/lib/middleware/proxy.js
@@ -45,7 +45,12 @@ var parseProxyConfig = function(proxies, config) {
     if (!proxyConfig[proxyPath].port) {
       if (!proxyConfig[proxyPath].host) {
         proxyConfig[proxyPath].host = config.hostname;
-        proxyConfig[proxyPath].port = config.port;
+        Object.defineProperty(proxyConfig[proxyPath], 'port', {
+          get: function() {
+            return config.port;
+         },
+        });
       } else {
         proxyConfig[proxyPath].port = proxyConfig[proxyPath].https ? '443' : '80';
       }
```

### LINKED ISSUE #3011: EADDRINUSE error leads to improper port usage by server middleware
### Expected behaviour
If a port is changed in the passed configuration before server start (e.g. if `EADDRINUSE` is thrown for a specified port, the next available is used), it should be respected by server middleware.
### Actual behaviour
Middleware use a port that was initially passed in the configuration.
### Environment Details

- Karma version (output of `karma --version`): reproduced in 1.7.1, but should be also actual for 2.0.2
- Relevant part of your `karma.config.js` file: proxy middleware can be used as an example
```js
proxies: {
  '/img/': '/base/test/images/'
},
port: <specify already used port>
```
### Steps to reproduce the behaviour

1. Run karma instance (`karma start`) with already used port – in other words you have to raise `EADDRINUSE` error in https://github.com/karma-runner/karma/blob/667b47efbe42800189efc9ba697f07c2671a7845/lib/server.js#L186 It can be reproduced by running 2 or more karma instances that use the same port (e.g. `9876`)
2. You have to see Karma warning: `WARN [karma]: Port 9876 in use` 
and a new port that Karma uses: `INFO [karma]: Karma <v> server started at http://0.0.0.0:9877/`

image

3. Try to load any resources that match proxy rules.
4. Resources are proxied to the initial port `9876` instead of changed `9877`.

### PR DESCRIPTION
**Pull request by lusarz**
- create NetUtils with `isPortAvailable` and `getAvailablePort` methods
- use NetUtils to search for available port before starting server and build middlewares
- remove handler for `EADDRINUSE` error - with `NetUtils.getAvailablePort` we'll know that port is available for sure, so this error would no raise

### CODE REVIEW

File: lib/server.js [hunk 1]
```diff
@@ -96,7 +97,22 @@ class Server extends KarmaEventEmitter {
...
+    ])
+      .then(() => {
+        const config = this.get('config')
+        return NetUtils.getAvailablePort(config.port).then((port) => {
+          config.port = port
+          this._injector.invoke(this._start, this)
+        })
+      })
+      .catch((error) => {
+        this.log.error('Front-end script compile failed with error: ' + error)
```
Comment (johnjbarton) [inline lib/server.js]: I think using log4js for fatal errors is insufficient: the message gives no stack trace pointing to the problem.
How about adding `console.error('Front-end script compile failed with error: \n', error)` (note comma).

File: lib/server.js [hunk 2]
```diff
@@ -124,47 +140,28 @@ class Server extends KarmaEventEmitter {
...
-    webServer.on('error', (e) => {
-      if (e.code === 'EADDRINUSE') {
-        this.log.warn('Port %d in use', config.port)
-        config.port++
-        webServer.listen(config.port, config.listenAddress)
-      } else {
-        throw e
-      }
-    })
+    webServer.on('error', (e) => { throw e })
```
Comment (johnjbarton) [inline lib/server.js]: As a reader I have to ponder what will happen here.  Maybe we can have a `dieOnError(err)` function that  calls log4js, console.error and the process exit dance, then use it here and the compile fail.

Comment (lusarz) [reply lib/server.js]: I definitely agree, but I'm not sure this pull request is right place to do it. It may require more investigation.

File: lib/server.js (hunk 1 above)
Comment (lusarz) [reply lib/server.js]: Done

File: lib/utils/net-utils.js [hunk 3]
```diff
@@ -0,0 +1,25 @@
+const net = require('net')
+
+const NetUtils = {
+  isPortAvailable (port) {
+    return new Promise((resolve) => {
+      const server = net.createServer()
+
+      server.unref()
+      server.on('error', () => resolve(false))
```
Comment (sergei-startsev) [inline lib/utils/net-utils.js]: I suppose we have to check `EADDRINUSE`, `EACCES` codes, otherwise reject the promise and terminate karma:
```js
.on('error', function(e) {
    if (e.code != 'EADDRINUSE' && e.code!='EACCES'){
        return reject(e);
    }
    resolve(false)
```

File: lib/utils/net-utils.js [hunk 4]
```diff
@@ -0,0 +1,25 @@
...
+
+      server.listen({ port }, () => {
```
Comment (sergei-startsev) [inline lib/utils/net-utils.js]: We have to know whether a process is listening on a port, not just whether the port was available. These aren't exactly the same thing. I believe you also have to specify the host to prevent `EACCES`:
```js
 server.listen(port, '0.0.0.0', ()=>{...});
```

File: lib/utils/net-utils.js (hunk 3 above)
Comment (lusarz) [reply lib/utils/net-utils.js]: Do you mean any specific situation when such check would be relevant ?

File: lib/utils/net-utils.js (hunk 4 above)
Comment (lusarz) [reply lib/utils/net-utils.js]: Thanks, good point with host - I've updated pull request.

I think `isPortAvailable` function actually checks whether other process is listening on a port. `isPortAvailable` try to run server, if everything is ok it close server and resolves with true. 

It seems to be enough, but I may miss something.

File: lib/utils/net-utils.js (hunk 3 above)
Comment (sergei-startsev) [reply lib/utils/net-utils.js]: As an example you could specify invalid `listenAddress` in karma.config: `listenAddress: '123'`. It should fail with `EADDRNOTAVAIL` error.

Comment (sergei-startsev) [reply lib/utils/net-utils.js]: So, I suppose it would be safer to limit checks using known errors related to port usage.

File: lib/utils/net-utils.js [hunk 5]
```diff
@@ -0,0 +1,25 @@
...
+      server.listen(port, listenAddress, () => {
+        server.close(() => resolve(true))
+      })
+    })
+  },
+
+  getAvailablePort (port, listenAddress) {
+    return NetUtils.isPortAvailable(port, listenAddress).then((available) => {
+      if (available) return Promise.resolve(port)
+      else return NetUtils.getAvailablePort(port + 1)
```
Comment (johnjbarton) [inline lib/utils/net-utils.js]: If `config.port` starts out of bounds for ports (> 65535), then we will loop until the test times out somehow. This will appear as a hang.  I think we should at least log on the else path. Maybe we should limit the quest to say 100 calls.

Comment (sergei-startsev) [reply lib/utils/net-utils.js]: @johnjbarton there will be `RangeError` for ports start out of bounds:
```
RangeError: "port" argument must be >= 0 and < 65536
```
So I think the approach suggested above will also work properly here:
```js
if (e.code != 'EADDRINUSE' && e.code!='EACCES'){
    return reject(e);
}
```

Comment (johnjbarton) [reply lib/utils/net-utils.js]: ok great. (I'm unclear on the state of the code here so I'll let you do the merge when ready)

File: lib/utils/net-utils.js (hunk 3 above)
Comment (lusarz) [reply lib/utils/net-utils.js]: @sergei-startsev 
I've updated pull request with your suggestion. What do you think about current solution ?

File: lib/server.js [hunk 6]
```diff
@@ -47,6 +48,12 @@ function createSocketIoServer (webServer, executor, config) {
   return server
 }
 
+function dieOnError (error) {
+  console.error(error)
```
Comment (sergei-startsev) [inline lib/server.js]: should it be `this.log.error` instead?

File: lib/server.js [hunk 7]
```diff
@@ -124,47 +140,28 @@ class Server extends KarmaEventEmitter {
...
+        if (config.browsers && config.browsers.length) {
+          this._injector.invoke(launcher.launch, launcher).forEach((browserLauncher) => {
+            singleRunDoneBrowsers[browserLauncher.id] = false
           })
-        })
-        .catch((error) => {
-          this.log.error('Front-end script compile failed with error: ' + error)
+        }
+        if (this.loadErrors.length > 0) {
+          this.log.error('Found %d load error%s', this.loadErrors.length, this.loadErrors.length === 1 ? '' : 's')
```
Comment (sergei-startsev) [inline lib/server.js]: could `dieOnError` be used here?

File: lib/server.js [hunk 8]
```diff
@@ -96,7 +103,16 @@ class Server extends KarmaEventEmitter {
   }
 
   start () {
-    this._injector.invoke(this._start, this)
+    return Promise.all([
+      BundleUtils.bundleResourceIfNotExist('client/main.js', 'static/karma.js'),
+      BundleUtils.bundleResourceIfNotExist('context/main.js', 'static/context.js')
+    ])
+      .then(() => NetUtils.getAvailablePort(this.get('config.port'), this.get('config.listenAddress')))
```
Comment (sergei-startsev) [inline lib/server.js]: does it reasonable to get `config` and reuse it below instead of getting it each time?
```js
const config = this.get('config')
...
.then(() => NetUtils.getAvailablePort(config.port, config.listenAddress))
...
config.port = port
```

File: lib/utils/net-utils.js [hunk 9]
```diff
@@ -0,0 +1,43 @@
...
+const net = require('net')
+
+const NetUtils = {
+  isPortAvailable (port, listenAddress) {
+    return new Promise((resolve, reject) => {
+      const server = net.createServer()
+
+      server.unref()
+      server.on('error', (err) => {
+        server.close()
```
Comment (sergei-startsev) [inline lib/utils/net-utils.js]: I suppose it's redundant

File: lib/utils/net-utils.js [hunk 10]
```diff
@@ -0,0 +1,43 @@
...
+      })
+
+      server.listen(port, listenAddress, () => {
+        server.close(() => resolve(true))
+      })
+    })
+  },
+
+  getAvailablePort (port, listenAddress, maxAttempts = 10) {
+    if (!maxAttempts) {
```
Comment (sergei-startsev) [inline lib/utils/net-utils.js]: I believe you can omit this check since you've added `err.code === 'EADDRINUSE' || err.code === 'EACCES'` check. 10 attempts aren't enough if you have hundreds test suites and you would like to parallelize them on multi-core machine

File: test/unit/utils/net-utils.spec.js [hunk 11]
```diff
@@ -0,0 +1,64 @@
+'use strict'
+
+const NetUtils = require('../../../lib/utils/net-utils')
+const connect = require('connect')
+const http = require('http')
```
Comment (sergei-startsev) [inline test/unit/utils/net-utils.spec.js]: might use `net` server, it's not so heavy

File: lib/utils/net-utils.js (hunk 3 above)
Comment (sergei-startsev) [reply lib/utils/net-utils.js]: @lusarz thanks for the updates, I've left a few more comments that might be useful.

File: lib/utils/net-utils.js (hunk 9 above)
Comment (lusarz) [reply lib/utils/net-utils.js]: Are you sure ? I see in nodejs documentation (a bit above https://nodejs.org/api/net.html#net_server_listen_handle_backlog_callback) that author invoke `server.close()` inside `server.on('error', (e) => {})` - to be honest I don't know why and whether it's necessary.

File: lib/utils/net-utils.js (hunk 10 above)
Comment (lusarz) [reply lib/utils/net-utils.js]: Alright, `RangeError` should save us here. I'm gonna remove this `maxAttempts` check.

File: lib/server.js (hunk 6 above)
Comment (lusarz) [reply lib/server.js]: @johnjbarton suggested here:
https://github.com/karma-runner/karma/pull/3039#discussion_r194440585

to use `console.error` to log fatal errors. I think it's ok.

File: lib/utils/net-utils.js (hunk 9 above)
Comment (sergei-startsev) [reply lib/utils/net-utils.js]: https://nodejs.org/api/net.html#net_event_error
well, it seems reasonable to leave it

File: lib/server.js (hunk 6 above)
Comment (sergei-startsev) [reply lib/server.js]: hmm... I suppose `this.log.error` was initially used here https://github.com/karma-runner/karma/pull/3039/files/193ccdd1147b58ee2117322a105155aea064827e#diff-c945a46d13b34fcaff544d966cffcabaL157

If we would like to replace `this.log.error` by `console.error` for fatal errors, it should be consistent across the module, see https://github.com/karma-runner/karma/pull/3039/files/193ccdd1147b58ee2117322a105155aea064827e#diff-c945a46d13b34fcaff544d966cffcabaR160

Otherwise I would leave the existing behavior in that PR.

File: lib/server.js (hunk 7 above)
Comment (lusarz) [reply lib/server.js]: Updated

File: lib/server.js (hunk 8 above)
Comment (lusarz) [reply lib/server.js]: Updated

File: lib/utils/net-utils.js (hunk 10 above)
Comment (lusarz) [reply lib/utils/net-utils.js]: Fixed

File: test/unit/utils/net-utils.spec.js (hunk 11 above)
Comment (lusarz) [reply test/unit/utils/net-utils.spec.js]: Good point, fixed

File: lib/server.js (hunk 6 above)
Comment (lusarz) [reply lib/server.js]: I've used `dieOnError` for that case now. Now use of `console.error` for fatal errors is consistent in this module.

File: test/unit/utils/net-utils.spec.js [hunk 12]
```diff
@@ -0,0 +1,50 @@
+'use strict'
+
+const NetUtils = require('../../../lib/utils/net-utils')
+const connect = require('connect')
+const http = require('net')
```
Comment (sergei-startsev) [inline test/unit/utils/net-utils.spec.js]:
```js
const net = require('net')
```

File: lib/utils/net-utils.js [hunk 13]
```diff
@@ -0,0 +1,39 @@
...
+      })
+    })
+  },
+
+  getAvailablePort (port, listenAddress) {
+    return NetUtils.isPortAvailable(port, listenAddress)
+      .then((available) => {
+        if (available) {
+          return port
+        } else {
```
Comment (sergei-startsev) [inline lib/utils/net-utils.js]: `else` is redundant
